name: churn-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow==2.13.0
    - scikit-learn==1.3.0
    - pandas==2.0.3
    - numpy==1.24.3
    - joblib==1.3.2