name: CI Model Training & Docker Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file:./mlruns
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: pip install "mlflow==2.13.0"

      - name: Create Conda environment from file
        run: conda env create -f MLProject/conda.yaml

      - name: Run MLflow Project
        id: mlflow_run
        run: |
          # Set environment variables untuk MLflow
          export MLFLOW_TRACKING_URI="file:$(pwd)/mlruns"
          export MLFLOW_DEFAULT_ARTIFACT_ROOT="$(pwd)/mlruns"
          
          # Jalankan mlflow project
          conda run -n churn-env -e MLFLOW_TRACKING_URI -e MLFLOW_DEFAULT_ARTIFACT_ROOT mlflow run ./MLProject > run_output.txt
          
          # Ekstrak Run ID
          RUN_ID=$(cat run_output.txt | grep "run ID" | awk '{print $NF}')
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV
          echo "Training completed. Run ID: ${RUN_ID}"
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction-api:latest"